version: '3.8'

services:

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "14268:14268"
      - "16686:16686"

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: minio_user
      MINIO_ROOT_PASSWORD: minio_pass
    command: server --console-address ":9001" /data

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minio_user minio_pass;
      /usr/bin/mc mb myminio/images;
      /usr/bin/mc policy set public myminio/images;
      /usr/bin/mc policy set download myminio/images;
      /usr/bin/mc anonymous set public myminio/images;

      exit 0;
      "

  pg:
    image: postgres:15.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev_pass
      POSTGRES_DB: jungle-test
    restart: on-failure
    volumes:
      - pg_data:/var/lib/postgresql/data

    ports:
      - "5432:5432"

    healthcheck:
      test: pg_isready -U postgres -d jungle-test
      interval: 1s
      timeout: 3s
      retries: 15

  migrate:
    image: migrate/migrate

    restart: on-failure

    depends_on:
      pg:
        condition: service_healthy

    volumes:
      - ./migration:/migrations

    command:
      [ "-database",  "postgres://postgres:dev_pass@pg:5432/jungle-test?sslmode=disable" , "-path", "/migrations", "up" ]

  app:
    build: .
    depends_on:
      migrate:
          condition: service_completed_successfully
      jaeger:
        condition: service_started
      minio:
        condition: service_started
    volumes:
      - ./keys:/keys
    ports:
      - "8080:8080"
      - "8082:8082"
    env_file:
      - .env
volumes:
  pg_data:
  minio_storage: